if(OPENMP)
  find_package(OpenMP)
  # if(OpenMP_CXX_FOUND)
      # target_link_libraries(${TARGET} PRIVATE OpenMP::OpenMP_CXX)
  # endif(OpenMP_CXX_FOUND)
  if (OPENMP_FOUND)
    string(APPEND CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    # string(APPEND CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  endif(OPENMP_FOUND)
endif(OPENMP)